const templateTag = require('./templateTag');

const gender = 'female';
const isReact = true;
const isLastLine = false;

const input = templateTag`
Good Morning, ${gender === 'female' ? 'miss' : 'mister'}!

${isReact && 'This is react app template generator'}

${isLastLine && 'This last line will not be shown'}
`;

const output = `
Good Morning, miss!

This is react app template generator
`;

test('test generated by templateTag string', () => {
	expect(input).toBe(output.trimLeft());
});
